spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isms-db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: meddourisami10@gmail.com
    password: fhhk vcqp pzxz htfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: 97+QV3nciNx0YyAMlxv5J52geazGGcbEq76MihsqlkkI0oGdYlZ0gcjg5YAI1Kgm0Gxv1n2tEpHuHfkFAx12ZA==   # Move this to environment variable in production!

storage:
  path: uploads/templates